// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/sample/sample.proto

package sample

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SampleRequest contains the input payload for sample RPC calls.
type SampleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SampleRequest) Reset() {
	*x = SampleRequest{}
	mi := &file_proto_sample_sample_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SampleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SampleRequest) ProtoMessage() {}

func (x *SampleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sample_sample_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SampleRequest.ProtoReflect.Descriptor instead.
func (*SampleRequest) Descriptor() ([]byte, []int) {
	return file_proto_sample_sample_proto_rawDescGZIP(), []int{0}
}

func (x *SampleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// SampleResponse contains the response payload returned by sample RPC calls.
type SampleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SampleResponse) Reset() {
	*x = SampleResponse{}
	mi := &file_proto_sample_sample_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SampleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SampleResponse) ProtoMessage() {}

func (x *SampleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sample_sample_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SampleResponse.ProtoReflect.Descriptor instead.
func (*SampleResponse) Descriptor() ([]byte, []int) {
	return file_proto_sample_sample_proto_rawDescGZIP(), []int{1}
}

func (x *SampleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_sample_sample_proto protoreflect.FileDescriptor

const file_proto_sample_sample_proto_rawDesc = "" +
	"\n" +
	"\x19proto/sample/sample.proto\x12\x06sample\"#\n" +
	"\rSampleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"*\n" +
	"\x0eSampleResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2N\n" +
	"\rSampleService\x12=\n" +
	"\fSampleMethod\x12\x15.sample.SampleRequest\x1a\x16.sample.SampleResponseB\x1eZ\x1cmangahub/proto/sample;sampleb\x06proto3"

var (
	file_proto_sample_sample_proto_rawDescOnce sync.Once
	file_proto_sample_sample_proto_rawDescData []byte
)

func file_proto_sample_sample_proto_rawDescGZIP() []byte {
	file_proto_sample_sample_proto_rawDescOnce.Do(func() {
		file_proto_sample_sample_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sample_sample_proto_rawDesc), len(file_proto_sample_sample_proto_rawDesc)))
	})
	return file_proto_sample_sample_proto_rawDescData
}

var file_proto_sample_sample_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_sample_sample_proto_goTypes = []any{
	(*SampleRequest)(nil),  // 0: sample.SampleRequest
	(*SampleResponse)(nil), // 1: sample.SampleResponse
}
var file_proto_sample_sample_proto_depIdxs = []int32{
	0, // 0: sample.SampleService.SampleMethod:input_type -> sample.SampleRequest
	1, // 1: sample.SampleService.SampleMethod:output_type -> sample.SampleResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_sample_sample_proto_init() }
func file_proto_sample_sample_proto_init() {
	if File_proto_sample_sample_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sample_sample_proto_rawDesc), len(file_proto_sample_sample_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sample_sample_proto_goTypes,
		DependencyIndexes: file_proto_sample_sample_proto_depIdxs,
		MessageInfos:      file_proto_sample_sample_proto_msgTypes,
	}.Build()
	File_proto_sample_sample_proto = out.File
	file_proto_sample_sample_proto_goTypes = nil
	file_proto_sample_sample_proto_depIdxs = nil
}
