// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/user_manga/user_manga.proto

package user_manga

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	manga "mangahub/proto/manga"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Follow / Unfollow
type FollowMangaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MangaId       string                 `protobuf:"bytes,2,opt,name=manga_id,json=mangaId,proto3" json:"manga_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowMangaRequest) Reset() {
	*x = FollowMangaRequest{}
	mi := &file_proto_user_manga_user_manga_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowMangaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowMangaRequest) ProtoMessage() {}

func (x *FollowMangaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_manga_user_manga_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowMangaRequest.ProtoReflect.Descriptor instead.
func (*FollowMangaRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_manga_user_manga_proto_rawDescGZIP(), []int{0}
}

func (x *FollowMangaRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FollowMangaRequest) GetMangaId() string {
	if x != nil {
		return x.MangaId
	}
	return ""
}

type FollowMangaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MangaId       string                 `protobuf:"bytes,2,opt,name=manga_id,json=mangaId,proto3" json:"manga_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowMangaResponse) Reset() {
	*x = FollowMangaResponse{}
	mi := &file_proto_user_manga_user_manga_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowMangaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowMangaResponse) ProtoMessage() {}

func (x *FollowMangaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_manga_user_manga_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowMangaResponse.ProtoReflect.Descriptor instead.
func (*FollowMangaResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_manga_user_manga_proto_rawDescGZIP(), []int{1}
}

func (x *FollowMangaResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FollowMangaResponse) GetMangaId() string {
	if x != nil {
		return x.MangaId
	}
	return ""
}

func (x *FollowMangaResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type UnfollowMangaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MangaId       string                 `protobuf:"bytes,2,opt,name=manga_id,json=mangaId,proto3" json:"manga_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfollowMangaRequest) Reset() {
	*x = UnfollowMangaRequest{}
	mi := &file_proto_user_manga_user_manga_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowMangaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowMangaRequest) ProtoMessage() {}

func (x *UnfollowMangaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_manga_user_manga_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowMangaRequest.ProtoReflect.Descriptor instead.
func (*UnfollowMangaRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_manga_user_manga_proto_rawDescGZIP(), []int{2}
}

func (x *UnfollowMangaRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UnfollowMangaRequest) GetMangaId() string {
	if x != nil {
		return x.MangaId
	}
	return ""
}

type UnfollowMangaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfollowMangaResponse) Reset() {
	*x = UnfollowMangaResponse{}
	mi := &file_proto_user_manga_user_manga_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowMangaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowMangaResponse) ProtoMessage() {}

func (x *UnfollowMangaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_manga_user_manga_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowMangaResponse.ProtoReflect.Descriptor instead.
func (*UnfollowMangaResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_manga_user_manga_proto_rawDescGZIP(), []int{3}
}

func (x *UnfollowMangaResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Get Following Mangas
type GetFollowingMangasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowingMangasRequest) Reset() {
	*x = GetFollowingMangasRequest{}
	mi := &file_proto_user_manga_user_manga_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowingMangasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowingMangasRequest) ProtoMessage() {}

func (x *GetFollowingMangasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_manga_user_manga_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowingMangasRequest.ProtoReflect.Descriptor instead.
func (*GetFollowingMangasRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_manga_user_manga_proto_rawDescGZIP(), []int{4}
}

func (x *GetFollowingMangasRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetFollowingMangasRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetFollowingMangasRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetFollowingMangasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mangas        []*manga.Manga         `protobuf:"bytes,1,rep,name=mangas,proto3" json:"mangas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowingMangasResponse) Reset() {
	*x = GetFollowingMangasResponse{}
	mi := &file_proto_user_manga_user_manga_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowingMangasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowingMangasResponse) ProtoMessage() {}

func (x *GetFollowingMangasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_manga_user_manga_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowingMangasResponse.ProtoReflect.Descriptor instead.
func (*GetFollowingMangasResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_manga_user_manga_proto_rawDescGZIP(), []int{5}
}

func (x *GetFollowingMangasResponse) GetMangas() []*manga.Manga {
	if x != nil {
		return x.Mangas
	}
	return nil
}

// Store Reading Progress
type StoreReadingProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ChapterId     string                 `protobuf:"bytes,2,opt,name=chapter_id,json=chapterId,proto3" json:"chapter_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreReadingProgressRequest) Reset() {
	*x = StoreReadingProgressRequest{}
	mi := &file_proto_user_manga_user_manga_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreReadingProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreReadingProgressRequest) ProtoMessage() {}

func (x *StoreReadingProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_manga_user_manga_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreReadingProgressRequest.ProtoReflect.Descriptor instead.
func (*StoreReadingProgressRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_manga_user_manga_proto_rawDescGZIP(), []int{6}
}

func (x *StoreReadingProgressRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StoreReadingProgressRequest) GetChapterId() string {
	if x != nil {
		return x.ChapterId
	}
	return ""
}

type StoreReadingProgressResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MangaId        string                 `protobuf:"bytes,2,opt,name=manga_id,json=mangaId,proto3" json:"manga_id,omitempty"`
	Status         string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	CurrentChapter int32                  `protobuf:"varint,4,opt,name=current_chapter,json=currentChapter,proto3" json:"current_chapter,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StoreReadingProgressResponse) Reset() {
	*x = StoreReadingProgressResponse{}
	mi := &file_proto_user_manga_user_manga_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreReadingProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreReadingProgressResponse) ProtoMessage() {}

func (x *StoreReadingProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_manga_user_manga_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreReadingProgressResponse.ProtoReflect.Descriptor instead.
func (*StoreReadingProgressResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_manga_user_manga_proto_rawDescGZIP(), []int{7}
}

func (x *StoreReadingProgressResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StoreReadingProgressResponse) GetMangaId() string {
	if x != nil {
		return x.MangaId
	}
	return ""
}

func (x *StoreReadingProgressResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StoreReadingProgressResponse) GetCurrentChapter() int32 {
	if x != nil {
		return x.CurrentChapter
	}
	return 0
}

func (x *StoreReadingProgressResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *StoreReadingProgressResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// Get Reading History
type GetReadingHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReadingHistoryRequest) Reset() {
	*x = GetReadingHistoryRequest{}
	mi := &file_proto_user_manga_user_manga_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReadingHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReadingHistoryRequest) ProtoMessage() {}

func (x *GetReadingHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_manga_user_manga_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReadingHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetReadingHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_manga_user_manga_proto_rawDescGZIP(), []int{8}
}

func (x *GetReadingHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetReadingHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetReadingHistoryRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ReadingHistoryItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Manga          *manga.Manga           `protobuf:"bytes,1,opt,name=manga,proto3" json:"manga,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	CurrentChapter int32                  `protobuf:"varint,3,opt,name=current_chapter,json=currentChapter,proto3" json:"current_chapter,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReadingHistoryItem) Reset() {
	*x = ReadingHistoryItem{}
	mi := &file_proto_user_manga_user_manga_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadingHistoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadingHistoryItem) ProtoMessage() {}

func (x *ReadingHistoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_manga_user_manga_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadingHistoryItem.ProtoReflect.Descriptor instead.
func (*ReadingHistoryItem) Descriptor() ([]byte, []int) {
	return file_proto_user_manga_user_manga_proto_rawDescGZIP(), []int{9}
}

func (x *ReadingHistoryItem) GetManga() *manga.Manga {
	if x != nil {
		return x.Manga
	}
	return nil
}

func (x *ReadingHistoryItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReadingHistoryItem) GetCurrentChapter() int32 {
	if x != nil {
		return x.CurrentChapter
	}
	return 0
}

func (x *ReadingHistoryItem) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *ReadingHistoryItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetReadingHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	History       []*ReadingHistoryItem  `protobuf:"bytes,1,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReadingHistoryResponse) Reset() {
	*x = GetReadingHistoryResponse{}
	mi := &file_proto_user_manga_user_manga_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReadingHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReadingHistoryResponse) ProtoMessage() {}

func (x *GetReadingHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_manga_user_manga_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReadingHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetReadingHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_manga_user_manga_proto_rawDescGZIP(), []int{10}
}

func (x *GetReadingHistoryResponse) GetHistory() []*ReadingHistoryItem {
	if x != nil {
		return x.History
	}
	return nil
}

var File_proto_user_manga_user_manga_proto protoreflect.FileDescriptor

const file_proto_user_manga_user_manga_proto_rawDesc = "" +
	"\n" +
	"!proto/user_manga/user_manga.proto\x12\n" +
	"user_manga\x1a\x17proto/manga/manga.proto\"H\n" +
	"\x12FollowMangaRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bmanga_id\x18\x02 \x01(\tR\amangaId\"h\n" +
	"\x13FollowMangaResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bmanga_id\x18\x02 \x01(\tR\amangaId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\"J\n" +
	"\x14UnfollowMangaRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bmanga_id\x18\x02 \x01(\tR\amangaId\"1\n" +
	"\x15UnfollowMangaResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"b\n" +
	"\x19GetFollowingMangasRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"B\n" +
	"\x1aGetFollowingMangasResponse\x12$\n" +
	"\x06mangas\x18\x01 \x03(\v2\f.manga.MangaR\x06mangas\"U\n" +
	"\x1bStoreReadingProgressRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"chapter_id\x18\x02 \x01(\tR\tchapterId\"\xd1\x01\n" +
	"\x1cStoreReadingProgressResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bmanga_id\x18\x02 \x01(\tR\amangaId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12'\n" +
	"\x0fcurrent_chapter\x18\x04 \x01(\x05R\x0ecurrentChapter\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"a\n" +
	"\x18GetReadingHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"\xb7\x01\n" +
	"\x12ReadingHistoryItem\x12\"\n" +
	"\x05manga\x18\x01 \x01(\v2\f.manga.MangaR\x05manga\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12'\n" +
	"\x0fcurrent_chapter\x18\x03 \x01(\x05R\x0ecurrentChapter\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"U\n" +
	"\x19GetReadingHistoryResponse\x128\n" +
	"\ahistory\x18\x01 \x03(\v2\x1e.user_manga.ReadingHistoryItemR\ahistory2\xee\x03\n" +
	"\x14GRPCUserMangaService\x12N\n" +
	"\vFollowManga\x12\x1e.user_manga.FollowMangaRequest\x1a\x1f.user_manga.FollowMangaResponse\x12T\n" +
	"\rUnfollowManga\x12 .user_manga.UnfollowMangaRequest\x1a!.user_manga.UnfollowMangaResponse\x12c\n" +
	"\x12GetFollowingMangas\x12%.user_manga.GetFollowingMangasRequest\x1a&.user_manga.GetFollowingMangasResponse\x12i\n" +
	"\x14StoreReadingProgress\x12'.user_manga.StoreReadingProgressRequest\x1a(.user_manga.StoreReadingProgressResponse\x12`\n" +
	"\x11GetReadingHistory\x12$.user_manga.GetReadingHistoryRequest\x1a%.user_manga.GetReadingHistoryResponseB&Z$mangahub/proto/user_manga;user_mangab\x06proto3"

var (
	file_proto_user_manga_user_manga_proto_rawDescOnce sync.Once
	file_proto_user_manga_user_manga_proto_rawDescData []byte
)

func file_proto_user_manga_user_manga_proto_rawDescGZIP() []byte {
	file_proto_user_manga_user_manga_proto_rawDescOnce.Do(func() {
		file_proto_user_manga_user_manga_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_user_manga_user_manga_proto_rawDesc), len(file_proto_user_manga_user_manga_proto_rawDesc)))
	})
	return file_proto_user_manga_user_manga_proto_rawDescData
}

var file_proto_user_manga_user_manga_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_user_manga_user_manga_proto_goTypes = []any{
	(*FollowMangaRequest)(nil),           // 0: user_manga.FollowMangaRequest
	(*FollowMangaResponse)(nil),          // 1: user_manga.FollowMangaResponse
	(*UnfollowMangaRequest)(nil),         // 2: user_manga.UnfollowMangaRequest
	(*UnfollowMangaResponse)(nil),        // 3: user_manga.UnfollowMangaResponse
	(*GetFollowingMangasRequest)(nil),    // 4: user_manga.GetFollowingMangasRequest
	(*GetFollowingMangasResponse)(nil),   // 5: user_manga.GetFollowingMangasResponse
	(*StoreReadingProgressRequest)(nil),  // 6: user_manga.StoreReadingProgressRequest
	(*StoreReadingProgressResponse)(nil), // 7: user_manga.StoreReadingProgressResponse
	(*GetReadingHistoryRequest)(nil),     // 8: user_manga.GetReadingHistoryRequest
	(*ReadingHistoryItem)(nil),           // 9: user_manga.ReadingHistoryItem
	(*GetReadingHistoryResponse)(nil),    // 10: user_manga.GetReadingHistoryResponse
	(*manga.Manga)(nil),                  // 11: manga.Manga
}
var file_proto_user_manga_user_manga_proto_depIdxs = []int32{
	11, // 0: user_manga.GetFollowingMangasResponse.mangas:type_name -> manga.Manga
	11, // 1: user_manga.ReadingHistoryItem.manga:type_name -> manga.Manga
	9,  // 2: user_manga.GetReadingHistoryResponse.history:type_name -> user_manga.ReadingHistoryItem
	0,  // 3: user_manga.GRPCUserMangaService.FollowManga:input_type -> user_manga.FollowMangaRequest
	2,  // 4: user_manga.GRPCUserMangaService.UnfollowManga:input_type -> user_manga.UnfollowMangaRequest
	4,  // 5: user_manga.GRPCUserMangaService.GetFollowingMangas:input_type -> user_manga.GetFollowingMangasRequest
	6,  // 6: user_manga.GRPCUserMangaService.StoreReadingProgress:input_type -> user_manga.StoreReadingProgressRequest
	8,  // 7: user_manga.GRPCUserMangaService.GetReadingHistory:input_type -> user_manga.GetReadingHistoryRequest
	1,  // 8: user_manga.GRPCUserMangaService.FollowManga:output_type -> user_manga.FollowMangaResponse
	3,  // 9: user_manga.GRPCUserMangaService.UnfollowManga:output_type -> user_manga.UnfollowMangaResponse
	5,  // 10: user_manga.GRPCUserMangaService.GetFollowingMangas:output_type -> user_manga.GetFollowingMangasResponse
	7,  // 11: user_manga.GRPCUserMangaService.StoreReadingProgress:output_type -> user_manga.StoreReadingProgressResponse
	10, // 12: user_manga.GRPCUserMangaService.GetReadingHistory:output_type -> user_manga.GetReadingHistoryResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_user_manga_user_manga_proto_init() }
func file_proto_user_manga_user_manga_proto_init() {
	if File_proto_user_manga_user_manga_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_manga_user_manga_proto_rawDesc), len(file_proto_user_manga_user_manga_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_user_manga_user_manga_proto_goTypes,
		DependencyIndexes: file_proto_user_manga_user_manga_proto_depIdxs,
		MessageInfos:      file_proto_user_manga_user_manga_proto_msgTypes,
	}.Build()
	File_proto_user_manga_user_manga_proto = out.File
	file_proto_user_manga_user_manga_proto_goTypes = nil
	file_proto_user_manga_user_manga_proto_depIdxs = nil
}
