// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/user_manga/user_manga.proto

package user_manga

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GRPCUserMangaService_FollowManga_FullMethodName          = "/user_manga.GRPCUserMangaService/FollowManga"
	GRPCUserMangaService_UnfollowManga_FullMethodName        = "/user_manga.GRPCUserMangaService/UnfollowManga"
	GRPCUserMangaService_GetFollowingMangas_FullMethodName   = "/user_manga.GRPCUserMangaService/GetFollowingMangas"
	GRPCUserMangaService_StoreReadingProgress_FullMethodName = "/user_manga.GRPCUserMangaService/StoreReadingProgress"
	GRPCUserMangaService_GetReadingHistory_FullMethodName    = "/user_manga.GRPCUserMangaService/GetReadingHistory"
)

// GRPCUserMangaServiceClient is the client API for GRPCUserMangaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GRPCUserMangaServiceClient interface {
	FollowManga(ctx context.Context, in *FollowMangaRequest, opts ...grpc.CallOption) (*FollowMangaResponse, error)
	UnfollowManga(ctx context.Context, in *UnfollowMangaRequest, opts ...grpc.CallOption) (*UnfollowMangaResponse, error)
	GetFollowingMangas(ctx context.Context, in *GetFollowingMangasRequest, opts ...grpc.CallOption) (*GetFollowingMangasResponse, error)
	StoreReadingProgress(ctx context.Context, in *StoreReadingProgressRequest, opts ...grpc.CallOption) (*StoreReadingProgressResponse, error)
	GetReadingHistory(ctx context.Context, in *GetReadingHistoryRequest, opts ...grpc.CallOption) (*GetReadingHistoryResponse, error)
}

type gRPCUserMangaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGRPCUserMangaServiceClient(cc grpc.ClientConnInterface) GRPCUserMangaServiceClient {
	return &gRPCUserMangaServiceClient{cc}
}

func (c *gRPCUserMangaServiceClient) FollowManga(ctx context.Context, in *FollowMangaRequest, opts ...grpc.CallOption) (*FollowMangaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FollowMangaResponse)
	err := c.cc.Invoke(ctx, GRPCUserMangaService_FollowManga_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gRPCUserMangaServiceClient) UnfollowManga(ctx context.Context, in *UnfollowMangaRequest, opts ...grpc.CallOption) (*UnfollowMangaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnfollowMangaResponse)
	err := c.cc.Invoke(ctx, GRPCUserMangaService_UnfollowManga_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gRPCUserMangaServiceClient) GetFollowingMangas(ctx context.Context, in *GetFollowingMangasRequest, opts ...grpc.CallOption) (*GetFollowingMangasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFollowingMangasResponse)
	err := c.cc.Invoke(ctx, GRPCUserMangaService_GetFollowingMangas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gRPCUserMangaServiceClient) StoreReadingProgress(ctx context.Context, in *StoreReadingProgressRequest, opts ...grpc.CallOption) (*StoreReadingProgressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreReadingProgressResponse)
	err := c.cc.Invoke(ctx, GRPCUserMangaService_StoreReadingProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gRPCUserMangaServiceClient) GetReadingHistory(ctx context.Context, in *GetReadingHistoryRequest, opts ...grpc.CallOption) (*GetReadingHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReadingHistoryResponse)
	err := c.cc.Invoke(ctx, GRPCUserMangaService_GetReadingHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GRPCUserMangaServiceServer is the server API for GRPCUserMangaService service.
// All implementations must embed UnimplementedGRPCUserMangaServiceServer
// for forward compatibility.
type GRPCUserMangaServiceServer interface {
	FollowManga(context.Context, *FollowMangaRequest) (*FollowMangaResponse, error)
	UnfollowManga(context.Context, *UnfollowMangaRequest) (*UnfollowMangaResponse, error)
	GetFollowingMangas(context.Context, *GetFollowingMangasRequest) (*GetFollowingMangasResponse, error)
	StoreReadingProgress(context.Context, *StoreReadingProgressRequest) (*StoreReadingProgressResponse, error)
	GetReadingHistory(context.Context, *GetReadingHistoryRequest) (*GetReadingHistoryResponse, error)
	mustEmbedUnimplementedGRPCUserMangaServiceServer()
}

// UnimplementedGRPCUserMangaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGRPCUserMangaServiceServer struct{}

func (UnimplementedGRPCUserMangaServiceServer) FollowManga(context.Context, *FollowMangaRequest) (*FollowMangaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FollowManga not implemented")
}
func (UnimplementedGRPCUserMangaServiceServer) UnfollowManga(context.Context, *UnfollowMangaRequest) (*UnfollowMangaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnfollowManga not implemented")
}
func (UnimplementedGRPCUserMangaServiceServer) GetFollowingMangas(context.Context, *GetFollowingMangasRequest) (*GetFollowingMangasResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFollowingMangas not implemented")
}
func (UnimplementedGRPCUserMangaServiceServer) StoreReadingProgress(context.Context, *StoreReadingProgressRequest) (*StoreReadingProgressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StoreReadingProgress not implemented")
}
func (UnimplementedGRPCUserMangaServiceServer) GetReadingHistory(context.Context, *GetReadingHistoryRequest) (*GetReadingHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReadingHistory not implemented")
}
func (UnimplementedGRPCUserMangaServiceServer) mustEmbedUnimplementedGRPCUserMangaServiceServer() {}
func (UnimplementedGRPCUserMangaServiceServer) testEmbeddedByValue()                              {}

// UnsafeGRPCUserMangaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GRPCUserMangaServiceServer will
// result in compilation errors.
type UnsafeGRPCUserMangaServiceServer interface {
	mustEmbedUnimplementedGRPCUserMangaServiceServer()
}

func RegisterGRPCUserMangaServiceServer(s grpc.ServiceRegistrar, srv GRPCUserMangaServiceServer) {
	// If the following call panics, it indicates UnimplementedGRPCUserMangaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GRPCUserMangaService_ServiceDesc, srv)
}

func _GRPCUserMangaService_FollowManga_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowMangaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCUserMangaServiceServer).FollowManga(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GRPCUserMangaService_FollowManga_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCUserMangaServiceServer).FollowManga(ctx, req.(*FollowMangaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GRPCUserMangaService_UnfollowManga_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnfollowMangaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCUserMangaServiceServer).UnfollowManga(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GRPCUserMangaService_UnfollowManga_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCUserMangaServiceServer).UnfollowManga(ctx, req.(*UnfollowMangaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GRPCUserMangaService_GetFollowingMangas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFollowingMangasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCUserMangaServiceServer).GetFollowingMangas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GRPCUserMangaService_GetFollowingMangas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCUserMangaServiceServer).GetFollowingMangas(ctx, req.(*GetFollowingMangasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GRPCUserMangaService_StoreReadingProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreReadingProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCUserMangaServiceServer).StoreReadingProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GRPCUserMangaService_StoreReadingProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCUserMangaServiceServer).StoreReadingProgress(ctx, req.(*StoreReadingProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GRPCUserMangaService_GetReadingHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReadingHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCUserMangaServiceServer).GetReadingHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GRPCUserMangaService_GetReadingHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCUserMangaServiceServer).GetReadingHistory(ctx, req.(*GetReadingHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GRPCUserMangaService_ServiceDesc is the grpc.ServiceDesc for GRPCUserMangaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GRPCUserMangaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user_manga.GRPCUserMangaService",
	HandlerType: (*GRPCUserMangaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FollowManga",
			Handler:    _GRPCUserMangaService_FollowManga_Handler,
		},
		{
			MethodName: "UnfollowManga",
			Handler:    _GRPCUserMangaService_UnfollowManga_Handler,
		},
		{
			MethodName: "GetFollowingMangas",
			Handler:    _GRPCUserMangaService_GetFollowingMangas_Handler,
		},
		{
			MethodName: "StoreReadingProgress",
			Handler:    _GRPCUserMangaService_StoreReadingProgress_Handler,
		},
		{
			MethodName: "GetReadingHistory",
			Handler:    _GRPCUserMangaService_GetReadingHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/user_manga/user_manga.proto",
}
