// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/session/session.proto

package session

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GRPCSessionService_SaveSession_FullMethodName   = "/session.GRPCSessionService/SaveSession"
	GRPCSessionService_UpdateSession_FullMethodName = "/session.GRPCSessionService/UpdateSession"
)

// GRPCSessionServiceClient is the client API for GRPCSessionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GRPCSessionService provides RPC endpoints for session management.
type GRPCSessionServiceClient interface {
	// SaveSession saves a user session with access and refresh tokens.
	SaveSession(ctx context.Context, in *SaveSessionRequest, opts ...grpc.CallOption) (*SaveSessionResponse, error)
	// UpdateSession updates an existing session for a user.
	UpdateSession(ctx context.Context, in *UpdateSessionRequest, opts ...grpc.CallOption) (*UpdateSessionResponse, error)
}

type gRPCSessionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGRPCSessionServiceClient(cc grpc.ClientConnInterface) GRPCSessionServiceClient {
	return &gRPCSessionServiceClient{cc}
}

func (c *gRPCSessionServiceClient) SaveSession(ctx context.Context, in *SaveSessionRequest, opts ...grpc.CallOption) (*SaveSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveSessionResponse)
	err := c.cc.Invoke(ctx, GRPCSessionService_SaveSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gRPCSessionServiceClient) UpdateSession(ctx context.Context, in *UpdateSessionRequest, opts ...grpc.CallOption) (*UpdateSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSessionResponse)
	err := c.cc.Invoke(ctx, GRPCSessionService_UpdateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GRPCSessionServiceServer is the server API for GRPCSessionService service.
// All implementations must embed UnimplementedGRPCSessionServiceServer
// for forward compatibility.
//
// GRPCSessionService provides RPC endpoints for session management.
type GRPCSessionServiceServer interface {
	// SaveSession saves a user session with access and refresh tokens.
	SaveSession(context.Context, *SaveSessionRequest) (*SaveSessionResponse, error)
	// UpdateSession updates an existing session for a user.
	UpdateSession(context.Context, *UpdateSessionRequest) (*UpdateSessionResponse, error)
	mustEmbedUnimplementedGRPCSessionServiceServer()
}

// UnimplementedGRPCSessionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGRPCSessionServiceServer struct{}

func (UnimplementedGRPCSessionServiceServer) SaveSession(context.Context, *SaveSessionRequest) (*SaveSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveSession not implemented")
}
func (UnimplementedGRPCSessionServiceServer) UpdateSession(context.Context, *UpdateSessionRequest) (*UpdateSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSession not implemented")
}
func (UnimplementedGRPCSessionServiceServer) mustEmbedUnimplementedGRPCSessionServiceServer() {}
func (UnimplementedGRPCSessionServiceServer) testEmbeddedByValue()                            {}

// UnsafeGRPCSessionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GRPCSessionServiceServer will
// result in compilation errors.
type UnsafeGRPCSessionServiceServer interface {
	mustEmbedUnimplementedGRPCSessionServiceServer()
}

func RegisterGRPCSessionServiceServer(s grpc.ServiceRegistrar, srv GRPCSessionServiceServer) {
	// If the following call panics, it indicates UnimplementedGRPCSessionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GRPCSessionService_ServiceDesc, srv)
}

func _GRPCSessionService_SaveSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCSessionServiceServer).SaveSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GRPCSessionService_SaveSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCSessionServiceServer).SaveSession(ctx, req.(*SaveSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GRPCSessionService_UpdateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCSessionServiceServer).UpdateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GRPCSessionService_UpdateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCSessionServiceServer).UpdateSession(ctx, req.(*UpdateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GRPCSessionService_ServiceDesc is the grpc.ServiceDesc for GRPCSessionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GRPCSessionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "session.GRPCSessionService",
	HandlerType: (*GRPCSessionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveSession",
			Handler:    _GRPCSessionService_SaveSession_Handler,
		},
		{
			MethodName: "UpdateSession",
			Handler:    _GRPCSessionService_UpdateSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/session/session.proto",
}
