// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/chapter/chapter.proto

package chapter

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetChapterByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChapterId     string                 `protobuf:"bytes,1,opt,name=chapter_id,json=chapterId,proto3" json:"chapter_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChapterByIDRequest) Reset() {
	*x = GetChapterByIDRequest{}
	mi := &file_proto_chapter_chapter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChapterByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChapterByIDRequest) ProtoMessage() {}

func (x *GetChapterByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chapter_chapter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChapterByIDRequest.ProtoReflect.Descriptor instead.
func (*GetChapterByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_chapter_chapter_proto_rawDescGZIP(), []int{0}
}

func (x *GetChapterByIDRequest) GetChapterId() string {
	if x != nil {
		return x.ChapterId
	}
	return ""
}

type GetChapterByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MangaId       string                 `protobuf:"bytes,2,opt,name=manga_id,json=mangaId,proto3" json:"manga_id,omitempty"`
	ChapterNumber float64                `protobuf:"fixed64,3,opt,name=chapter_number,json=chapterNumber,proto3" json:"chapter_number,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	PagesData     string                 `protobuf:"bytes,5,opt,name=pages_data,json=pagesData,proto3" json:"pages_data,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChapterByIDResponse) Reset() {
	*x = GetChapterByIDResponse{}
	mi := &file_proto_chapter_chapter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChapterByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChapterByIDResponse) ProtoMessage() {}

func (x *GetChapterByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chapter_chapter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChapterByIDResponse.ProtoReflect.Descriptor instead.
func (*GetChapterByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_chapter_chapter_proto_rawDescGZIP(), []int{1}
}

func (x *GetChapterByIDResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetChapterByIDResponse) GetMangaId() string {
	if x != nil {
		return x.MangaId
	}
	return ""
}

func (x *GetChapterByIDResponse) GetChapterNumber() float64 {
	if x != nil {
		return x.ChapterNumber
	}
	return 0
}

func (x *GetChapterByIDResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetChapterByIDResponse) GetPagesData() string {
	if x != nil {
		return x.PagesData
	}
	return ""
}

func (x *GetChapterByIDResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetChapterByIDResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreateChapterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MangaId       string                 `protobuf:"bytes,2,opt,name=manga_id,json=mangaId,proto3" json:"manga_id,omitempty"`
	ChapterNumber float64                `protobuf:"fixed64,3,opt,name=chapter_number,json=chapterNumber,proto3" json:"chapter_number,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	PagesData     string                 `protobuf:"bytes,5,opt,name=pages_data,json=pagesData,proto3" json:"pages_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChapterRequest) Reset() {
	*x = CreateChapterRequest{}
	mi := &file_proto_chapter_chapter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChapterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChapterRequest) ProtoMessage() {}

func (x *CreateChapterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chapter_chapter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChapterRequest.ProtoReflect.Descriptor instead.
func (*CreateChapterRequest) Descriptor() ([]byte, []int) {
	return file_proto_chapter_chapter_proto_rawDescGZIP(), []int{2}
}

func (x *CreateChapterRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateChapterRequest) GetMangaId() string {
	if x != nil {
		return x.MangaId
	}
	return ""
}

func (x *CreateChapterRequest) GetChapterNumber() float64 {
	if x != nil {
		return x.ChapterNumber
	}
	return 0
}

func (x *CreateChapterRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateChapterRequest) GetPagesData() string {
	if x != nil {
		return x.PagesData
	}
	return ""
}

type CreateChapterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChapterResponse) Reset() {
	*x = CreateChapterResponse{}
	mi := &file_proto_chapter_chapter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChapterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChapterResponse) ProtoMessage() {}

func (x *CreateChapterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chapter_chapter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChapterResponse.ProtoReflect.Descriptor instead.
func (*CreateChapterResponse) Descriptor() ([]byte, []int) {
	return file_proto_chapter_chapter_proto_rawDescGZIP(), []int{3}
}

func (x *CreateChapterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateChapterResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_proto_chapter_chapter_proto protoreflect.FileDescriptor

const file_proto_chapter_chapter_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/chapter/chapter.proto\x12\achapter\"6\n" +
	"\x15GetChapterByIDRequest\x12\x1d\n" +
	"\n" +
	"chapter_id\x18\x01 \x01(\tR\tchapterId\"\xdd\x01\n" +
	"\x16GetChapterByIDResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bmanga_id\x18\x02 \x01(\tR\amangaId\x12%\n" +
	"\x0echapter_number\x18\x03 \x01(\x01R\rchapterNumber\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"pages_data\x18\x05 \x01(\tR\tpagesData\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\"\x9d\x01\n" +
	"\x14CreateChapterRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bmanga_id\x18\x02 \x01(\tR\amangaId\x12%\n" +
	"\x0echapter_number\x18\x03 \x01(\x01R\rchapterNumber\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"pages_data\x18\x05 \x01(\tR\tpagesData\"A\n" +
	"\x15CreateChapterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id2\xb7\x01\n" +
	"\x12GRPCChapterService\x12Q\n" +
	"\x0eGetChapterByID\x12\x1e.chapter.GetChapterByIDRequest\x1a\x1f.chapter.GetChapterByIDResponse\x12N\n" +
	"\rCreateChapter\x12\x1d.chapter.CreateChapterRequest\x1a\x1e.chapter.CreateChapterResponseB\x18Z\x16mangahub/proto/chapterb\x06proto3"

var (
	file_proto_chapter_chapter_proto_rawDescOnce sync.Once
	file_proto_chapter_chapter_proto_rawDescData []byte
)

func file_proto_chapter_chapter_proto_rawDescGZIP() []byte {
	file_proto_chapter_chapter_proto_rawDescOnce.Do(func() {
		file_proto_chapter_chapter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_chapter_chapter_proto_rawDesc), len(file_proto_chapter_chapter_proto_rawDesc)))
	})
	return file_proto_chapter_chapter_proto_rawDescData
}

var file_proto_chapter_chapter_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_chapter_chapter_proto_goTypes = []any{
	(*GetChapterByIDRequest)(nil),  // 0: chapter.GetChapterByIDRequest
	(*GetChapterByIDResponse)(nil), // 1: chapter.GetChapterByIDResponse
	(*CreateChapterRequest)(nil),   // 2: chapter.CreateChapterRequest
	(*CreateChapterResponse)(nil),  // 3: chapter.CreateChapterResponse
}
var file_proto_chapter_chapter_proto_depIdxs = []int32{
	0, // 0: chapter.GRPCChapterService.GetChapterByID:input_type -> chapter.GetChapterByIDRequest
	2, // 1: chapter.GRPCChapterService.CreateChapter:input_type -> chapter.CreateChapterRequest
	1, // 2: chapter.GRPCChapterService.GetChapterByID:output_type -> chapter.GetChapterByIDResponse
	3, // 3: chapter.GRPCChapterService.CreateChapter:output_type -> chapter.CreateChapterResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_chapter_chapter_proto_init() }
func file_proto_chapter_chapter_proto_init() {
	if File_proto_chapter_chapter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_chapter_chapter_proto_rawDesc), len(file_proto_chapter_chapter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_chapter_chapter_proto_goTypes,
		DependencyIndexes: file_proto_chapter_chapter_proto_depIdxs,
		MessageInfos:      file_proto_chapter_chapter_proto_msgTypes,
	}.Build()
	File_proto_chapter_chapter_proto = out.File
	file_proto_chapter_chapter_proto_goTypes = nil
	file_proto_chapter_chapter_proto_depIdxs = nil
}
