// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/chapter/chapter.proto

package chapter

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GRPCChapterService_GetChapterByID_FullMethodName = "/chapter.GRPCChapterService/GetChapterByID"
	GRPCChapterService_CreateChapter_FullMethodName  = "/chapter.GRPCChapterService/CreateChapter"
)

// GRPCChapterServiceClient is the client API for GRPCChapterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GRPCChapterServiceClient interface {
	GetChapterByID(ctx context.Context, in *GetChapterByIDRequest, opts ...grpc.CallOption) (*GetChapterByIDResponse, error)
	CreateChapter(ctx context.Context, in *CreateChapterRequest, opts ...grpc.CallOption) (*CreateChapterResponse, error)
}

type gRPCChapterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGRPCChapterServiceClient(cc grpc.ClientConnInterface) GRPCChapterServiceClient {
	return &gRPCChapterServiceClient{cc}
}

func (c *gRPCChapterServiceClient) GetChapterByID(ctx context.Context, in *GetChapterByIDRequest, opts ...grpc.CallOption) (*GetChapterByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChapterByIDResponse)
	err := c.cc.Invoke(ctx, GRPCChapterService_GetChapterByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gRPCChapterServiceClient) CreateChapter(ctx context.Context, in *CreateChapterRequest, opts ...grpc.CallOption) (*CreateChapterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateChapterResponse)
	err := c.cc.Invoke(ctx, GRPCChapterService_CreateChapter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GRPCChapterServiceServer is the server API for GRPCChapterService service.
// All implementations must embed UnimplementedGRPCChapterServiceServer
// for forward compatibility.
type GRPCChapterServiceServer interface {
	GetChapterByID(context.Context, *GetChapterByIDRequest) (*GetChapterByIDResponse, error)
	CreateChapter(context.Context, *CreateChapterRequest) (*CreateChapterResponse, error)
	mustEmbedUnimplementedGRPCChapterServiceServer()
}

// UnimplementedGRPCChapterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGRPCChapterServiceServer struct{}

func (UnimplementedGRPCChapterServiceServer) GetChapterByID(context.Context, *GetChapterByIDRequest) (*GetChapterByIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChapterByID not implemented")
}
func (UnimplementedGRPCChapterServiceServer) CreateChapter(context.Context, *CreateChapterRequest) (*CreateChapterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateChapter not implemented")
}
func (UnimplementedGRPCChapterServiceServer) mustEmbedUnimplementedGRPCChapterServiceServer() {}
func (UnimplementedGRPCChapterServiceServer) testEmbeddedByValue()                            {}

// UnsafeGRPCChapterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GRPCChapterServiceServer will
// result in compilation errors.
type UnsafeGRPCChapterServiceServer interface {
	mustEmbedUnimplementedGRPCChapterServiceServer()
}

func RegisterGRPCChapterServiceServer(s grpc.ServiceRegistrar, srv GRPCChapterServiceServer) {
	// If the following call panics, it indicates UnimplementedGRPCChapterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GRPCChapterService_ServiceDesc, srv)
}

func _GRPCChapterService_GetChapterByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChapterByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCChapterServiceServer).GetChapterByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GRPCChapterService_GetChapterByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCChapterServiceServer).GetChapterByID(ctx, req.(*GetChapterByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GRPCChapterService_CreateChapter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateChapterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCChapterServiceServer).CreateChapter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GRPCChapterService_CreateChapter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCChapterServiceServer).CreateChapter(ctx, req.(*CreateChapterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GRPCChapterService_ServiceDesc is the grpc.ServiceDesc for GRPCChapterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GRPCChapterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chapter.GRPCChapterService",
	HandlerType: (*GRPCChapterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetChapterByID",
			Handler:    _GRPCChapterService_GetChapterByID_Handler,
		},
		{
			MethodName: "CreateChapter",
			Handler:    _GRPCChapterService_CreateChapter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/chapter/chapter.proto",
}
