// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/manga/manga.proto

package manga

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Chapter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	ChapterNumber int32                  `protobuf:"varint,3,opt,name=chapter_number,json=chapterNumber,proto3" json:"chapter_number,omitempty"`
	PagesData     string                 `protobuf:"bytes,4,opt,name=pages_data,json=pagesData,proto3" json:"pages_data,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chapter) Reset() {
	*x = Chapter{}
	mi := &file_proto_manga_manga_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chapter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chapter) ProtoMessage() {}

func (x *Chapter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manga_manga_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chapter.ProtoReflect.Descriptor instead.
func (*Chapter) Descriptor() ([]byte, []int) {
	return file_proto_manga_manga_proto_rawDescGZIP(), []int{0}
}

func (x *Chapter) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Chapter) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Chapter) GetChapterNumber() int32 {
	if x != nil {
		return x.ChapterNumber
	}
	return 0
}

func (x *Chapter) GetPagesData() string {
	if x != nil {
		return x.PagesData
	}
	return ""
}

func (x *Chapter) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Chapter) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type Manga struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	TotalChapters int32                  `protobuf:"varint,4,opt,name=total_chapters,json=totalChapters,proto3" json:"total_chapters,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,6,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manga) Reset() {
	*x = Manga{}
	mi := &file_proto_manga_manga_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manga) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manga) ProtoMessage() {}

func (x *Manga) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manga_manga_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manga.ProtoReflect.Descriptor instead.
func (*Manga) Descriptor() ([]byte, []int) {
	return file_proto_manga_manga_proto_rawDescGZIP(), []int{1}
}

func (x *Manga) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Manga) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Manga) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Manga) GetTotalChapters() int32 {
	if x != nil {
		return x.TotalChapters
	}
	return 0
}

func (x *Manga) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Manga) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *Manga) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Manga) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Manga) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type MangaListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MangaListRequest) Reset() {
	*x = MangaListRequest{}
	mi := &file_proto_manga_manga_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MangaListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MangaListRequest) ProtoMessage() {}

func (x *MangaListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manga_manga_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MangaListRequest.ProtoReflect.Descriptor instead.
func (*MangaListRequest) Descriptor() ([]byte, []int) {
	return file_proto_manga_manga_proto_rawDescGZIP(), []int{2}
}

func (x *MangaListRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *MangaListRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type MangaListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mangas        []*Manga               `protobuf:"bytes,1,rep,name=mangas,proto3" json:"mangas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MangaListResponse) Reset() {
	*x = MangaListResponse{}
	mi := &file_proto_manga_manga_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MangaListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MangaListResponse) ProtoMessage() {}

func (x *MangaListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manga_manga_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MangaListResponse.ProtoReflect.Descriptor instead.
func (*MangaListResponse) Descriptor() ([]byte, []int) {
	return file_proto_manga_manga_proto_rawDescGZIP(), []int{3}
}

func (x *MangaListResponse) GetMangas() []*Manga {
	if x != nil {
		return x.Mangas
	}
	return nil
}

type MangaDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MangaDetailRequest) Reset() {
	*x = MangaDetailRequest{}
	mi := &file_proto_manga_manga_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MangaDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MangaDetailRequest) ProtoMessage() {}

func (x *MangaDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manga_manga_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MangaDetailRequest.ProtoReflect.Descriptor instead.
func (*MangaDetailRequest) Descriptor() ([]byte, []int) {
	return file_proto_manga_manga_proto_rawDescGZIP(), []int{4}
}

func (x *MangaDetailRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MangaDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manga         *Manga                 `protobuf:"bytes,1,opt,name=manga,proto3" json:"manga,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MangaDetailResponse) Reset() {
	*x = MangaDetailResponse{}
	mi := &file_proto_manga_manga_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MangaDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MangaDetailResponse) ProtoMessage() {}

func (x *MangaDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manga_manga_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MangaDetailResponse.ProtoReflect.Descriptor instead.
func (*MangaDetailResponse) Descriptor() ([]byte, []int) {
	return file_proto_manga_manga_proto_rawDescGZIP(), []int{5}
}

func (x *MangaDetailResponse) GetManga() *Manga {
	if x != nil {
		return x.Manga
	}
	return nil
}

type MangaChaptersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MangaChaptersRequest) Reset() {
	*x = MangaChaptersRequest{}
	mi := &file_proto_manga_manga_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MangaChaptersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MangaChaptersRequest) ProtoMessage() {}

func (x *MangaChaptersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manga_manga_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MangaChaptersRequest.ProtoReflect.Descriptor instead.
func (*MangaChaptersRequest) Descriptor() ([]byte, []int) {
	return file_proto_manga_manga_proto_rawDescGZIP(), []int{6}
}

func (x *MangaChaptersRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MangaChaptersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chapters      []*Chapter             `protobuf:"bytes,1,rep,name=chapters,proto3" json:"chapters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MangaChaptersResponse) Reset() {
	*x = MangaChaptersResponse{}
	mi := &file_proto_manga_manga_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MangaChaptersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MangaChaptersResponse) ProtoMessage() {}

func (x *MangaChaptersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manga_manga_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MangaChaptersResponse.ProtoReflect.Descriptor instead.
func (*MangaChaptersResponse) Descriptor() ([]byte, []int) {
	return file_proto_manga_manga_proto_rawDescGZIP(), []int{7}
}

func (x *MangaChaptersResponse) GetChapters() []*Chapter {
	if x != nil {
		return x.Chapters
	}
	return nil
}

type CheckMangaExistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckMangaExistsRequest) Reset() {
	*x = CheckMangaExistsRequest{}
	mi := &file_proto_manga_manga_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckMangaExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckMangaExistsRequest) ProtoMessage() {}

func (x *CheckMangaExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manga_manga_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckMangaExistsRequest.ProtoReflect.Descriptor instead.
func (*CheckMangaExistsRequest) Descriptor() ([]byte, []int) {
	return file_proto_manga_manga_proto_rawDescGZIP(), []int{8}
}

func (x *CheckMangaExistsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CheckMangaExistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckMangaExistsResponse) Reset() {
	*x = CheckMangaExistsResponse{}
	mi := &file_proto_manga_manga_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckMangaExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckMangaExistsResponse) ProtoMessage() {}

func (x *CheckMangaExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manga_manga_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckMangaExistsResponse.ProtoReflect.Descriptor instead.
func (*CheckMangaExistsResponse) Descriptor() ([]byte, []int) {
	return file_proto_manga_manga_proto_rawDescGZIP(), []int{9}
}

func (x *CheckMangaExistsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

var File_proto_manga_manga_proto protoreflect.FileDescriptor

const file_proto_manga_manga_proto_rawDesc = "" +
	"\n" +
	"\x17proto/manga/manga.proto\x12\x05manga\"\xb3\x01\n" +
	"\aChapter\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12%\n" +
	"\x0echapter_number\x18\x03 \x01(\x05R\rchapterNumber\x12\x1d\n" +
	"\n" +
	"pages_data\x18\x04 \x01(\tR\tpagesData\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"\x81\x02\n" +
	"\x05Manga\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12%\n" +
	"\x0etotal_chapters\x18\x04 \x01(\x05R\rtotalChapters\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1b\n" +
	"\tcover_url\x18\x06 \x01(\tR\bcoverUrl\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\"@\n" +
	"\x10MangaListRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"9\n" +
	"\x11MangaListResponse\x12$\n" +
	"\x06mangas\x18\x01 \x03(\v2\f.manga.MangaR\x06mangas\"$\n" +
	"\x12MangaDetailRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"9\n" +
	"\x13MangaDetailResponse\x12\"\n" +
	"\x05manga\x18\x01 \x01(\v2\f.manga.MangaR\x05manga\"&\n" +
	"\x14MangaChaptersRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"C\n" +
	"\x15MangaChaptersResponse\x12*\n" +
	"\bchapters\x18\x01 \x03(\v2\x0e.manga.ChapterR\bchapters\")\n" +
	"\x17CheckMangaExistsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"2\n" +
	"\x18CheckMangaExistsResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists2\xbf\x02\n" +
	"\x10GRPCMangaService\x12>\n" +
	"\tGetMangas\x12\x17.manga.MangaListRequest\x1a\x18.manga.MangaListResponse\x12G\n" +
	"\x0eGetMangaDetail\x12\x19.manga.MangaDetailRequest\x1a\x1a.manga.MangaDetailResponse\x12M\n" +
	"\x10GetMangaChapters\x12\x1b.manga.MangaChaptersRequest\x1a\x1c.manga.MangaChaptersResponse\x12S\n" +
	"\x10CheckMangaExists\x12\x1e.manga.CheckMangaExistsRequest\x1a\x1f.manga.CheckMangaExistsResponseB\x1cZ\x1amangahub/proto/manga;mangab\x06proto3"

var (
	file_proto_manga_manga_proto_rawDescOnce sync.Once
	file_proto_manga_manga_proto_rawDescData []byte
)

func file_proto_manga_manga_proto_rawDescGZIP() []byte {
	file_proto_manga_manga_proto_rawDescOnce.Do(func() {
		file_proto_manga_manga_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_manga_manga_proto_rawDesc), len(file_proto_manga_manga_proto_rawDesc)))
	})
	return file_proto_manga_manga_proto_rawDescData
}

var file_proto_manga_manga_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_manga_manga_proto_goTypes = []any{
	(*Chapter)(nil),                  // 0: manga.Chapter
	(*Manga)(nil),                    // 1: manga.Manga
	(*MangaListRequest)(nil),         // 2: manga.MangaListRequest
	(*MangaListResponse)(nil),        // 3: manga.MangaListResponse
	(*MangaDetailRequest)(nil),       // 4: manga.MangaDetailRequest
	(*MangaDetailResponse)(nil),      // 5: manga.MangaDetailResponse
	(*MangaChaptersRequest)(nil),     // 6: manga.MangaChaptersRequest
	(*MangaChaptersResponse)(nil),    // 7: manga.MangaChaptersResponse
	(*CheckMangaExistsRequest)(nil),  // 8: manga.CheckMangaExistsRequest
	(*CheckMangaExistsResponse)(nil), // 9: manga.CheckMangaExistsResponse
}
var file_proto_manga_manga_proto_depIdxs = []int32{
	1, // 0: manga.MangaListResponse.mangas:type_name -> manga.Manga
	1, // 1: manga.MangaDetailResponse.manga:type_name -> manga.Manga
	0, // 2: manga.MangaChaptersResponse.chapters:type_name -> manga.Chapter
	2, // 3: manga.GRPCMangaService.GetMangas:input_type -> manga.MangaListRequest
	4, // 4: manga.GRPCMangaService.GetMangaDetail:input_type -> manga.MangaDetailRequest
	6, // 5: manga.GRPCMangaService.GetMangaChapters:input_type -> manga.MangaChaptersRequest
	8, // 6: manga.GRPCMangaService.CheckMangaExists:input_type -> manga.CheckMangaExistsRequest
	3, // 7: manga.GRPCMangaService.GetMangas:output_type -> manga.MangaListResponse
	5, // 8: manga.GRPCMangaService.GetMangaDetail:output_type -> manga.MangaDetailResponse
	7, // 9: manga.GRPCMangaService.GetMangaChapters:output_type -> manga.MangaChaptersResponse
	9, // 10: manga.GRPCMangaService.CheckMangaExists:output_type -> manga.CheckMangaExistsResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_manga_manga_proto_init() }
func file_proto_manga_manga_proto_init() {
	if File_proto_manga_manga_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_manga_manga_proto_rawDesc), len(file_proto_manga_manga_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_manga_manga_proto_goTypes,
		DependencyIndexes: file_proto_manga_manga_proto_depIdxs,
		MessageInfos:      file_proto_manga_manga_proto_msgTypes,
	}.Build()
	File_proto_manga_manga_proto = out.File
	file_proto_manga_manga_proto_goTypes = nil
	file_proto_manga_manga_proto_depIdxs = nil
}
