// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/manga/manga.proto

package manga

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GRPCMangaService_GetMangas_FullMethodName        = "/manga.GRPCMangaService/GetMangas"
	GRPCMangaService_GetMangaDetail_FullMethodName   = "/manga.GRPCMangaService/GetMangaDetail"
	GRPCMangaService_GetMangaChapters_FullMethodName = "/manga.GRPCMangaService/GetMangaChapters"
	GRPCMangaService_CheckMangaExists_FullMethodName = "/manga.GRPCMangaService/CheckMangaExists"
)

// GRPCMangaServiceClient is the client API for GRPCMangaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GRPCMangaServiceClient interface {
	GetMangas(ctx context.Context, in *MangaListRequest, opts ...grpc.CallOption) (*MangaListResponse, error)
	GetMangaDetail(ctx context.Context, in *MangaDetailRequest, opts ...grpc.CallOption) (*MangaDetailResponse, error)
	GetMangaChapters(ctx context.Context, in *MangaChaptersRequest, opts ...grpc.CallOption) (*MangaChaptersResponse, error)
	CheckMangaExists(ctx context.Context, in *CheckMangaExistsRequest, opts ...grpc.CallOption) (*CheckMangaExistsResponse, error)
}

type gRPCMangaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGRPCMangaServiceClient(cc grpc.ClientConnInterface) GRPCMangaServiceClient {
	return &gRPCMangaServiceClient{cc}
}

func (c *gRPCMangaServiceClient) GetMangas(ctx context.Context, in *MangaListRequest, opts ...grpc.CallOption) (*MangaListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MangaListResponse)
	err := c.cc.Invoke(ctx, GRPCMangaService_GetMangas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gRPCMangaServiceClient) GetMangaDetail(ctx context.Context, in *MangaDetailRequest, opts ...grpc.CallOption) (*MangaDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MangaDetailResponse)
	err := c.cc.Invoke(ctx, GRPCMangaService_GetMangaDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gRPCMangaServiceClient) GetMangaChapters(ctx context.Context, in *MangaChaptersRequest, opts ...grpc.CallOption) (*MangaChaptersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MangaChaptersResponse)
	err := c.cc.Invoke(ctx, GRPCMangaService_GetMangaChapters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gRPCMangaServiceClient) CheckMangaExists(ctx context.Context, in *CheckMangaExistsRequest, opts ...grpc.CallOption) (*CheckMangaExistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckMangaExistsResponse)
	err := c.cc.Invoke(ctx, GRPCMangaService_CheckMangaExists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GRPCMangaServiceServer is the server API for GRPCMangaService service.
// All implementations must embed UnimplementedGRPCMangaServiceServer
// for forward compatibility.
type GRPCMangaServiceServer interface {
	GetMangas(context.Context, *MangaListRequest) (*MangaListResponse, error)
	GetMangaDetail(context.Context, *MangaDetailRequest) (*MangaDetailResponse, error)
	GetMangaChapters(context.Context, *MangaChaptersRequest) (*MangaChaptersResponse, error)
	CheckMangaExists(context.Context, *CheckMangaExistsRequest) (*CheckMangaExistsResponse, error)
	mustEmbedUnimplementedGRPCMangaServiceServer()
}

// UnimplementedGRPCMangaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGRPCMangaServiceServer struct{}

func (UnimplementedGRPCMangaServiceServer) GetMangas(context.Context, *MangaListRequest) (*MangaListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMangas not implemented")
}
func (UnimplementedGRPCMangaServiceServer) GetMangaDetail(context.Context, *MangaDetailRequest) (*MangaDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMangaDetail not implemented")
}
func (UnimplementedGRPCMangaServiceServer) GetMangaChapters(context.Context, *MangaChaptersRequest) (*MangaChaptersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMangaChapters not implemented")
}
func (UnimplementedGRPCMangaServiceServer) CheckMangaExists(context.Context, *CheckMangaExistsRequest) (*CheckMangaExistsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckMangaExists not implemented")
}
func (UnimplementedGRPCMangaServiceServer) mustEmbedUnimplementedGRPCMangaServiceServer() {}
func (UnimplementedGRPCMangaServiceServer) testEmbeddedByValue()                          {}

// UnsafeGRPCMangaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GRPCMangaServiceServer will
// result in compilation errors.
type UnsafeGRPCMangaServiceServer interface {
	mustEmbedUnimplementedGRPCMangaServiceServer()
}

func RegisterGRPCMangaServiceServer(s grpc.ServiceRegistrar, srv GRPCMangaServiceServer) {
	// If the following call panics, it indicates UnimplementedGRPCMangaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GRPCMangaService_ServiceDesc, srv)
}

func _GRPCMangaService_GetMangas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MangaListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCMangaServiceServer).GetMangas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GRPCMangaService_GetMangas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCMangaServiceServer).GetMangas(ctx, req.(*MangaListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GRPCMangaService_GetMangaDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MangaDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCMangaServiceServer).GetMangaDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GRPCMangaService_GetMangaDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCMangaServiceServer).GetMangaDetail(ctx, req.(*MangaDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GRPCMangaService_GetMangaChapters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MangaChaptersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCMangaServiceServer).GetMangaChapters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GRPCMangaService_GetMangaChapters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCMangaServiceServer).GetMangaChapters(ctx, req.(*MangaChaptersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GRPCMangaService_CheckMangaExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckMangaExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCMangaServiceServer).CheckMangaExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GRPCMangaService_CheckMangaExists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCMangaServiceServer).CheckMangaExists(ctx, req.(*CheckMangaExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GRPCMangaService_ServiceDesc is the grpc.ServiceDesc for GRPCMangaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GRPCMangaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "manga.GRPCMangaService",
	HandlerType: (*GRPCMangaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMangas",
			Handler:    _GRPCMangaService_GetMangas_Handler,
		},
		{
			MethodName: "GetMangaDetail",
			Handler:    _GRPCMangaService_GetMangaDetail_Handler,
		},
		{
			MethodName: "GetMangaChapters",
			Handler:    _GRPCMangaService_GetMangaChapters_Handler,
		},
		{
			MethodName: "CheckMangaExists",
			Handler:    _GRPCMangaService_CheckMangaExists_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/manga/manga.proto",
}
