// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/user/user.proto

package user

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GRPCUserService_GetUserModelByUsername_FullMethodName = "/user.GRPCUserService/GetUserModelByUsername"
	GRPCUserService_CreateNewUser_FullMethodName          = "/user.GRPCUserService/CreateNewUser"
	GRPCUserService_GetUserByID_FullMethodName            = "/user.GRPCUserService/GetUserByID"
)

// GRPCUserServiceClient is the client API for GRPCUserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GRPCUserService provides RPC endpoints related to user operations.
type GRPCUserServiceClient interface {
	// GetUserModelByUsername retrieves user information based on the provided username.
	GetUserModelByUsername(ctx context.Context, in *GetUserModelByUsernameRequest, opts ...grpc.CallOption) (*GetUserModelByUsernameResponse, error)
	// CreateNewUser creates a new user account.
	CreateNewUser(ctx context.Context, in *CreateNewUserRequest, opts ...grpc.CallOption) (*CreateNewUserResponse, error)
	// GetUserByID retrieves user information based on the provided user ID.
	GetUserByID(ctx context.Context, in *GetUserByIDRequest, opts ...grpc.CallOption) (*GetUserByIDResponse, error)
}

type gRPCUserServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGRPCUserServiceClient(cc grpc.ClientConnInterface) GRPCUserServiceClient {
	return &gRPCUserServiceClient{cc}
}

func (c *gRPCUserServiceClient) GetUserModelByUsername(ctx context.Context, in *GetUserModelByUsernameRequest, opts ...grpc.CallOption) (*GetUserModelByUsernameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserModelByUsernameResponse)
	err := c.cc.Invoke(ctx, GRPCUserService_GetUserModelByUsername_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gRPCUserServiceClient) CreateNewUser(ctx context.Context, in *CreateNewUserRequest, opts ...grpc.CallOption) (*CreateNewUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateNewUserResponse)
	err := c.cc.Invoke(ctx, GRPCUserService_CreateNewUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gRPCUserServiceClient) GetUserByID(ctx context.Context, in *GetUserByIDRequest, opts ...grpc.CallOption) (*GetUserByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserByIDResponse)
	err := c.cc.Invoke(ctx, GRPCUserService_GetUserByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GRPCUserServiceServer is the server API for GRPCUserService service.
// All implementations must embed UnimplementedGRPCUserServiceServer
// for forward compatibility.
//
// GRPCUserService provides RPC endpoints related to user operations.
type GRPCUserServiceServer interface {
	// GetUserModelByUsername retrieves user information based on the provided username.
	GetUserModelByUsername(context.Context, *GetUserModelByUsernameRequest) (*GetUserModelByUsernameResponse, error)
	// CreateNewUser creates a new user account.
	CreateNewUser(context.Context, *CreateNewUserRequest) (*CreateNewUserResponse, error)
	// GetUserByID retrieves user information based on the provided user ID.
	GetUserByID(context.Context, *GetUserByIDRequest) (*GetUserByIDResponse, error)
	mustEmbedUnimplementedGRPCUserServiceServer()
}

// UnimplementedGRPCUserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGRPCUserServiceServer struct{}

func (UnimplementedGRPCUserServiceServer) GetUserModelByUsername(context.Context, *GetUserModelByUsernameRequest) (*GetUserModelByUsernameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserModelByUsername not implemented")
}
func (UnimplementedGRPCUserServiceServer) CreateNewUser(context.Context, *CreateNewUserRequest) (*CreateNewUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNewUser not implemented")
}
func (UnimplementedGRPCUserServiceServer) GetUserByID(context.Context, *GetUserByIDRequest) (*GetUserByIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserByID not implemented")
}
func (UnimplementedGRPCUserServiceServer) mustEmbedUnimplementedGRPCUserServiceServer() {}
func (UnimplementedGRPCUserServiceServer) testEmbeddedByValue()                         {}

// UnsafeGRPCUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GRPCUserServiceServer will
// result in compilation errors.
type UnsafeGRPCUserServiceServer interface {
	mustEmbedUnimplementedGRPCUserServiceServer()
}

func RegisterGRPCUserServiceServer(s grpc.ServiceRegistrar, srv GRPCUserServiceServer) {
	// If the following call panics, it indicates UnimplementedGRPCUserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GRPCUserService_ServiceDesc, srv)
}

func _GRPCUserService_GetUserModelByUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserModelByUsernameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCUserServiceServer).GetUserModelByUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GRPCUserService_GetUserModelByUsername_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCUserServiceServer).GetUserModelByUsername(ctx, req.(*GetUserModelByUsernameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GRPCUserService_CreateNewUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNewUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCUserServiceServer).CreateNewUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GRPCUserService_CreateNewUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCUserServiceServer).CreateNewUser(ctx, req.(*CreateNewUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GRPCUserService_GetUserByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCUserServiceServer).GetUserByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GRPCUserService_GetUserByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCUserServiceServer).GetUserByID(ctx, req.(*GetUserByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GRPCUserService_ServiceDesc is the grpc.ServiceDesc for GRPCUserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GRPCUserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.GRPCUserService",
	HandlerType: (*GRPCUserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserModelByUsername",
			Handler:    _GRPCUserService_GetUserModelByUsername_Handler,
		},
		{
			MethodName: "CreateNewUser",
			Handler:    _GRPCUserService_CreateNewUser_Handler,
		},
		{
			MethodName: "GetUserByID",
			Handler:    _GRPCUserService_GetUserByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/user/user.proto",
}
